### ISSUE TITLE
used conmand line both taiyaki and RODAN

### ISSUE THREAD

**Issue by N-damo** [biodlab/RODAN#10]
I wonder whether you could provide used command line during training taiyaki and RODAN model.py.

for taiyaki:
train_flipflop.py ./mLstm_flipflop.py taiyaki-rna.hdf5 --size 256 --stride 10 --device cuda:0 --overwrite --winlen 31 --reverse

I am not sure whether I understand it correctly.
Thanks

**Comment by biodlab** [comment]
I am unsure what you are referring to. Taiyaki was used to generate the training data, not for actual rodan training.
