### ISSUE TITLE
Question regarding to accuracy measurement

### ISSUE THREAD

**Issue by WANGEOGEO** [biodlab/RODAN#2]
Hi,

I am wondering how accuracy measurement is carried out. This is my assumption about the pipeline, correct me if I am wrong, appreciation in advance:

1. Perform basecalling using a trained model, generate fasta file.
2. Generate SAM file using fasta file and reference genome file. (Using samtools I guess? Any other recommendation?)
3. Run accuracy.py to calculate accuracy.

**Comment by biodlab** [comment]
1. Basecalling using trained model generates fasta
2. Align to transcriptome (or reference) using minimap2
3. Run accuracy.py using the transcriptome and the sam (or bam) file
