### ISSUE TITLE
Question about basecalling accuracy

### ISSUE THREAD

**Issue by bio-detect** [biodlab/RODAN#3]
Hi:

 I have some doubts about basecalling results,wish to get your guidance.

I used the trained model that you have already published，the test dataset is human-dataset.After running many times using different dataset,I never get high accuracy.Accuracy is 50% or less.Do you have any suggestions for this?

**Comment by biodlab** [comment]
I need further details as to how you're running rodan and on what dataset. Specifically command line options which includes how you're checking accuracy. Also, what transcriptome/genome are you aligning the reference to, and how are you aligning? 

Basically I need details starting from what dataset you're using and all the commands you are running to produce whatever results you are getting. 

Also, according to your email:
"The sequences of RODAN prediction output  are ATCG.While Guppy prints AGCU base sequences.What's the base correspondence to achieve correct conversion?"

DNA is ACGT, and RNA is ACGU, so T (thymine) is replaced by U (uracil) in RNA.

You will generally see transcriptomes, eg gencode for humans, using ACGT.
