### ISSUE TITLE
Can the RODAN models be used with Dorado

### ISSUE THREAD

**Issue by hasindu2008** [biodlab/RODAN#4]
Hi

This might be a very silly question. Because RODAN is developed using pytorch and ONT's new opensource C++ base caller is based on torchlib (they do not have any RNA models in Dorado yet), I am wondering if there is a chance of using the trained model in RODAN with the Dorado?

**Comment by biodlab** [comment]
Sorry. Rodan is not compatible with Dorado as our model is stand alone.

**Comment by hasindu2008** [comment]
That is understandable, I was just wondering because when I ran RODAN on a PromethION dataset it runs for a long time. I haven't checked if RODAN installation I did is using the GPUs though.

**Comment by biodlab** [comment]
The basecaller defaults to the device "cuda", so as long as that device is available and pytorch is properly installed, it should work.
