### ISSUE TITLE
CPU bug torch.load with map_location

### ISSUE THREAD

**Issue by DelphIONe** [biodlab/RODAN#5]
Hy,

Thanks for your tool, I try to improve my RNA basecaller.
When I launch RODAN with
./basecall.py fast5/ > output_rodan.fasta

I obtain this error :
  File "/home/xxx/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I have modified the basecall.py with map_location=torch.device('cpu') but I don't be sure it's really applied.
Can you help me please ?
Thanks a lot,

**Comment by biodlab** [comment]
What do you mean "its really applied"? 

I should note that this will be incredibly slow if run on cpu.

**Comment by DelphIONe** [comment]
I switched on gpu, it's ok for the basecalling.
