### ISSUE TITLE
GPU usage & option to turn off adapter removal

### ISSUE THREAD

**Issue by ahfitzpa** [biodlab/RODAN#9]
Hi, 

I am really interested in applying this tool for direct RNA sequencing data after reading this [paper]( https://www.biorxiv.org/content/10.1101/2023.03.29.534691v2.full). Could you clarify in the documentation whether RODAN utilises GPU? Is there an option in this version of RODAN to turn of adapter trimming or can that option be introduced in newer versions of the tool?

**Comment by biodlab** [comment]
By default rodan utilizes gpu with pytorch and defaults to the first availablle cuda device. This can be changed by searching for torch.device.

There is no adapter trimming and no option to remove it.
